# Generated by Django 4.2.6 on 2023-10-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
