# Generated by Django 4.2.6 on 2023-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_idea_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='photo_1',
            field=models.ImageField(default=1, upload_to='idea/'),
            preserve_default=False,
        ),
    ]
