# Generated by Django 4.2.6 on 2023-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_idea_photo_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
