# Generated by Django 4.2.6 on 2023-10-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_idea_cat_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='dislike',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
