# Generated by Django 4.2.6 on 2023-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_idea_dislike_idea_like_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='choice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
