# Generated by Django 4.2.6 on 2023-10-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_voice_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
