# Generated by Django 4.2.6 on 2023-10-19 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_idea_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 5, 48, 44, 922229)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='choice',
            field=models.BooleanField(null=True),
        ),
    ]
