# Generated by Django 4.2.6 on 2023-10-20 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_idea_update_alter_voice_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='photo_4',
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 15, 41, 54, 75560)),
        ),
    ]
