# Generated by Django 4.2.6 on 2023-10-20 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_idea_photo_2_remove_idea_photo_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='photo_1',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 15, 42, 12, 219043)),
        ),
    ]
