# Generated by Django 4.2.6 on 2023-10-20 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_photo_1_idea_photo_alter_idea_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Write your comment on idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(help_text='Write here content of your idea', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='photo',
            field=models.ImageField(help_text='Put here image of your idea', upload_to='idea/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(help_text='Write here title of your idea', max_length=150),
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 16, 56, 28, 311180)),
        ),
    ]
