# Generated by Django 4.2.6 on 2023-10-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comment_content_alter_idea_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profle', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': 'Voice', 'verbose_name_plural': 'Voices'},
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 17, 36, 7, 63350)),
        ),
    ]
