# Generated by Django 4.2.6 on 2023-10-20 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 18, 15, 48, 191732)),
        ),
    ]
